### ISSUE TITLE
Strange sampling of voxels.

### ISSUE THREAD

**Issue by ddutchie** [pieroaccardi/Unity_PathTracing#2]
I have noticed that there are some strange artifacts when objects are touching, almost as if the last possible voxel for that object is not being traced. 

![image](https://user-images.githubusercontent.com/10877426/56092256-e8404e80-5eb9-11e9-9359-f3443bcb3427.png)

![image](https://user-images.githubusercontent.com/10877426/56092259-f8582e00-5eb9-11e9-8e0e-0cccdeb97c6d.png)

Looking into this, but have already managed to implement material sampling with an extra matrix4x4 buffer containing the material info.

**Comment by ddutchie** [comment]
Another example of this issue:

Scene View:
![image](https://user-images.githubusercontent.com/10877426/56093415-c39fa300-5ec8-11e9-9293-d0ef39abc871.png)

Tracing On:
![image](https://user-images.githubusercontent.com/10877426/56093416-d023fb80-5ec8-11e9-8b14-addb1da40104.png)

**Comment by ddutchie** [comment]
It looks like it has to do with an objects scale. If the plane's scale on the x and z is above 1 issues occur

**Comment by pieroaccardi** [comment]
I'll check it out

**Comment by ddutchie** [comment]
Thank you!
Another example of some of the artifacts:

Scene:
![image](https://user-images.githubusercontent.com/10877426/56094043-dc5f8700-5ecf-11e9-8a20-9cdeff19b16b.png)

Render:
![image](https://user-images.githubusercontent.com/10877426/56094039-d1a4f200-5ecf-11e9-902e-2be1458bc22a.png)

**Comment by ddutchie** [comment]
I'll add an example scene with the issues to my branch

**Comment by pieroaccardi** [comment]
should be fixed, let me know

**Comment by ddutchie** [comment]
Much better, although I still get some issues with small triangles?

![image](https://user-images.githubusercontent.com/10877426/56475794-bb79d180-648d-11e9-8470-12a5ee4b0409.png)


![image](https://user-images.githubusercontent.com/10877426/56475798-c9c7ed80-648d-11e9-8cc6-7a3a71f96f64.png)


Any ideas why this would be happening?
